@startuml
skinparam classAttributeIconSize 0

package cd_Parkhaus {

    interface Payment {

    }


    interface Parking {

    }


    interface OverlayAble {

    }


    interface System {

    }


    class PaymentProcess {

    }


    class ParkingSpace  {

    }


    class Overlay {

    }


    class SystemUse {

    }


    class Simulation {

    }


    class Manager {

    }


    abstract class Customer {

    }


    Payment <<interface>>
    Parking <<interface>>
    OverlayAble <<interface>>
    System <<interface>>
    Payment <|.. PaymentProcess
    Parking <|.. ParkingSpace
    Overlay <|.. OverlayAble
    System <|.. SystemUse
    Simulation <<entity>>
    Manager <<entity>>
    Customer <<entity>>



}


 @enduml