@startuml
skinparam classAttributeIconSize 0

package cd_Parkhaus {

    interface Payment {

    }


    interface Parking {

    }


    interface OverlayAble {

    }


    interface System {

    }


    class PaymentProcess {

    }


    class ParkingSpace  {

    }


    class Overlay {

    }


    class SystemUse {

    }


    class Simulation {

    }


    class Manager {

    }


    abstract class Customer {

    }





}


 @enduml