@startuml
actor Kunde

rectangle ConferenceInformationSystem {
  entity KundenInfo

  boundary SuchMaske
  boundary BuchungsMaske

  Kunde -right- SuchMaske
  Kunde -right- BuchungsMaske

  control CISController

  CISController .up.> SuchMaske
  CISController .left.> BuchungsMaske
  CISController ..> KundenInfo
}
@enduml