//Vorschläge sind willkommen =)

//DO TO: Die Implementierung des UML Diagramm für die Parkingspace.


@startuml
'https://plantuml.com/class-diagram

abstract Parkingspace{

   +ishandicap:boolean

   Parkingspace()
   Parkingspace(boolean value)

}

class Handicap{

}

Parkingspace<|--Handicap
Parkingspace<|--Firmen
Parkingspace<|--Tages
Parkingspace<|--Familien
Parkingspace<|--Frau


@enduml
