@startuml


left to right direction
skinparam packageStyle rectangle
actor User
agent HypoBank
agent EasyCard
agent CheckVisa

note right of CheckVisa
  check if User has viable visa
endnote

rectangle CIS {

  (filter)
  User  -> (login)
  User -> (register)
  (register) .. (login)

  (webinterface) .> (login) : <<include>>

  (webinterface) .> (conference information) : <<include>>

  note "Condition: User only wants specified information\nExtension Points: Use of filterrules for e-mails" as N1

  (filter) . N1
  N1 .> (conference information) : <<extend>>

  note "User receives e-mail of conferences" as N2
  (conference information) - N2
  N2 -> User

  note "Condition: User wants to book conference\nExtension Point: Book conference" as N3
  (book conference) . N3
  N3 .> (conference information): <<extend>>

  (national conference) .> (conference information) : <<extend>>
  (international conference) .> (conference information) : <<extend>>

  (national conference) .> (book conference) : <<include>>

  note "Condition: User has no visa\nExtension Point: Stop booking, send Error to User" as N4
  (book conference) .. N4
  N4 .> (international conference) : <<include>>

  (credit card) .> (book conference) : <<extend>>
  (ec-card) .> (book conference) : <<extend>>

  (credit card) - EasyCard
  (ec-card) - HypoBank
  (book conference) - CheckVisa


}

@enduml
// This is actual trash heh