@startuml
skinparam classAttributeIconSize 0

package cd_bookInternationalConference {

    interface ConferenceControllable {

    }

    class ConferenceController {

    }


    class memby {

    }


    interface BookingPageControllable {
        startSearchMask():boolean
    }

    class BookingPageController{
        #startSearchMask():boolean
    }


    interface SearchInternationalConferenceControllable {
        startSearchForX():boolean
        asHTML():boolean
    }

    class SearchInternationalConferenceController {
        #startSearchForX():boolean
        #asHTML():boolean
    }


    interface BookInternationalConferenceControllable {

    }

    class BookInternationalConferenceController {

    }


    interface InternationalConferenceDataBaseControllable {

    }

    class InternationalConferenceDataBaseController {
        #startSQLQuery():boolean
        #returnSQLQueryResults():boolean
    }


    interface VisaDataControllable {

    }

    class VisaDataController {

    }


    interface BookingPageable {
    startSearch():boolean

    }


    class BookingPage {
    +startSearch():boolean
    }


    interface SearchInternationalConferenceMaskable {
        showSearchMask():SearchMask
        enterKeywords(x):boolean
        startSearchForKeywords(x):boolean
        listOfResultsInHTML(): InternationalConferenceList
    }


    class SearchInternationalConferenceMask {
        #showSearchMask():SearchMask
        #enterKeywords(x):boolean
        #startSearchForKeywords(x):boolean
        #listOfResultsInHTML(): InternationalConferenceList
    }


    interface BookInternationalConferenceMaskable {

    }


    class BookInternationalConferenceMask {

    }


    interface CheckVisable {

    }


    class CheckVisa {

    }


    class InternationalConferenceList {

    }


    class VisaInfo {

    }


    class InternationalConferenceDataBase {
        #sqlQuery():boolean
    }


    class VisaDataBase {

    }






}
@enduml