@startuml
'https://plantuml.com/sequence-diagram
actor Customer
boundary index
boundary ManagementAuthenticationView
boundary ManagementView
boundary AverageRevenueByCustomerTypeChart
boundary AverageRevenueByVehicleTypeChart
boundary IncomeChart
boundary KundenChart
control ManagementAuthenticationServlet
control ManagementServlet
entity ManagementModel
Customer -> index : press MANAGEMENT-Button
index -> Level1Servlet : start ManagementAuthenticationMask
Level1Servlet -> ManagementAuthenticationView : show ManagementAuthenticationMask
ManagementAuthenticationView --> Customer : ManagementAuthenticationMask
Customer -> ManagementAuthenticationView : enter username and password
Customer -> ManagementAuthenticationView : start search for credentials(username, password)
ManagementAuthenticationView -> ManagementAuthenticationServlet : start search for username, password
ManagementAuthenticationView -> ManagementModel : filter-search for username, password
ManagementModel -> ManagementAuthenticationServlet : send results
alt credentials valid
    ManagementAuthenticationServlet --> ManagementView : handle success
    ManagementView --> Customer : show table with infos for all cars that left
    Customer -> ManagementServlet : press Button
    alt Total Revenue-Button
        ManagementServlet -> ManagementView : toggle total_revenue
        ManagementView -> Customer : display total_revenue
    end
    alt Average Revenue-Button
        ManagementServlet -> ManagementView : toggle average_revenue
        ManagementView -> Customer : display average_revenue
    end
    alt Current Cars-Button
        ManagementServlet -> ManagementView : toggle total_cars.size()
        ManagementView -> Customer : display total_cars.size()
    end
    alt Former Cars-Button
        ManagementServlet -> ManagementView : toggle former_cars.size()
        ManagementView -> Customer : display former_cars.size()
    end

end


@enduml