@startuml
'https://plantuml.com/class-diagram

abstract Parkingspace{



}

class Handicap{

}

Parkingspace<|--Handicap
Parkingspace<|--Firmen
Parkingspace<|--Tages
Parkingspace<|--Familien
Parkingspace<|--Frau


@enduml