@startuml
skinparam classAttributeIconSize 0

package cd_Parkhaus {

    interface Payment {

    }


    interface Parking {

    }


    interface OverlayAble {

    }


    interface System {

    }


    class PaymentProcess {
        + public CPaymentProcess( )
          + public payWithCreditCard ():boolean
          + public payWithSEPA():boolean
    }


    class ParkingSpace  {

     -private SpaceNo:int
     +public ParkingSpace()

    }


    class Overlay {

    }


    class SystemUse {

    }


    class Simulation {

    }


    class Manager {

    }


    abstract class Customer {

         -name:String
               -billNo:int
               -price:double
               public customergroup: String
               -disablity:boolean


          +public Customer(String Cname,int billNo, double price)

    }


    Payment <<interface>>
    Parking <<interface>>
    OverlayAble <<interface>>
    System <<interface>>
    Payment <|.. PaymentProcess
    Parking <|.. ParkingSpace
    OverlayAble <|.. Overlay
    System <|.. SystemUse
    Simulation <<entity>>
    Manager <<entity>>
    Customer <<entity>>



}


 @enduml