@startuml
'https://plantuml.com/class-diagram

abstract class DataBaseServlet {
}

    package Parkhaus {

        package cd_FilterHelpPage {


             interface helpPageIF {
                startHelpPage()
             }

             class helpPage {
                 + startHelpPage()
             }


             'the parameters makes the method failsafe
             interface helpSearchMaskIF {
                 sowHelpSearchMask(boolean b): helpSearchMask
                 enterKeywords(x)
                 startSearchForKeywords(x)
                 listOfResultsInHTML()
             }

             class helpSearchMask {
                 +showHelpSearchMask(boolean b): helpSearchMask
                 +enterKeywords(String x)
                 +startSearchForKeywords(String x)
                 +listOfResultsInHTML()
             }


             interface helpPageControllerIF {
                 startHelpMask()
             }

             class helpPageController {
                 +startHelpMask()
             }


             interface FAQDatabaseServletControllerIF {
                  startSearchingKeyword(String x)
                  sendResults(): SearchResultList
                  asHTML()
             }

             class FAQDatabaseServletController {
                  -searchResultList: SearchResultList
                  +startSearchingKeyword(String x)
                  +sendResults(): SearchResultList
                  +asHTML())
             }


             interface FAQDatabaseServletIF {
                  sqlQuery(): list<Object>

             }

             class FAQDataBaseServlet {
                  +sqlQuery()
             }


             class SearchResultList {
             }












         }



@enduml