@startuml
'https://plantuml.com/class-diagram

package cd_FilterHelpPage {

    package Parkhaus {

        package cd_FilterHelpPage {


             interface helpPageIF {
                 + startHelpPage(): boolean
             }

             class helpPage {
                 + startHelpPage(): boolean
             }


             interface helpPageControllerIF {
                 + showHelpMask(): boolean
             }

             class helpPageController {
                 + showHelpMask(): boolean
             }


             interface helpSearchMaskIF {
                 + getHelpSearchMask(boolean): helpSearchMask
                 'Up to debate and change Lukas 21.05.21
             }

             class helpSearchMask {
                 + getHelpSearchMask(boolean): helpSearchMask
             }


             class faqDataBaseServlet


         }

    }

@enduml