@startuml
'https://plantuml.com/class-diagram



    package Parkhaus {

        abstract class DataBaseServlet {
        }

        package cd_FilterHelpPage {


             interface HelpPageIF {
                startHelpPage()
             }

             class HelpPage {
                 +startHelpPage()
             }


             'the parameters makes the method failsafe
             interface HelpSearchMaskIF {
                 sowHelpSearchMask(boolean b): HelpSearchMask
                 enterKeywords(x)
                 startSearchForKeywords(x)
                 listOfResultsInHTML()
             }

             class HelpSearchMask {
                 +showHelpSearchMask(boolean b): HelpSearchMask
                 +enterKeywords(String x)
                 +startSearchForKeywords(String x)
                 +listOfResultsInHTML()
             }


             interface HelpPageControllerIF {
                 startHelpMask()
             }

             class HelpPageController {
                 +startHelpMask()
             }


             interface FAQDatabaseServletControllerIF {
                  startSearchingKeyword(String x)
                  sendResults(): SearchResultList
                  asHTML()
             }

             class FAQDatabaseServletController {
                  -searchResultList: SearchResultList
                  +startSearchingKeyword(String x)
                  +sendResults(): SearchResultList
                  +asHTML()
             }


             interface FAQDatabaseServletIF {
                  sqlQuery(): list<Object>
             }

             class FAQDataBaseServlet {
                  +sqlQuery()
             }


             class SearchResultList {
             }


             HelpPageIF <<interface>>
             HelpSearchMaskIF <<interface>>
             HelpPageControllerIF <<interface>>
             FAQDatabaseServletControllerIF <<interface>>
             FAQDatabaseServletIF <<interface>>
             DataBaseServlet <<abstract>>

             HelpPageIF <|.. HelpPage
             HelpSearchMaskIF <|.. HelpSearchMask
             HelpPageControllerIF <|.. HelpPageController
             FAQDatabaseServletControllerIF <|.. FAQDatabaseServletController
             FAQDatabaseServletIF  <|.. FAQDataBaseServlet
             DataBaseServlet <|-- FAQDataBaseServlet

         }
    }
    'created: 21.5.21: bella, lukas
    'changed: 24.5.21: bella, lukas, rahgawi



@enduml