@startuml

package Parkhaus {

actor customer as c
actor manager as m
control parkhausController

    rectangle PaymentProcess {
        boundary paymentPage
        control payController
        control ticketController
        entity customerInformation
        entity bill

        payController .up.> customerInformation
        payController .left.> paymentPage
        payController ..> bill

        ticketController .left.> payController

        c -up- paymentPage


    }

    rectangle Help {
        boundary helpPage
        boundary helpMask
        control helpController
        entity faq

        helpController ..> helpPage
        helpController ..> faq
        helpController ..> helpMask

        c -up- helpPage

        parkhausController ..> helpController


    }

    rectangle Management {

        boundary managementOverview
        control revenueController
        entity revenueList

        m -down- managementOverview
        revenueController ..> managementOverview
        revenueController ..> customerInformation
        revenueController ..> revenueList

    }

    rectangle ParkingSpace {

    }

    parkhausController .left.> payController


}

@enduml