@startuml

package Parkhaus {

actor customer as c
actor manager as m
control parkhausController
boundary parkhausMainPage

    rectangle PaymentProcess {
        boundary paymentPage
        control payController
        entity customerInformation
        entity bill

        payController .up.> customerInformation
        payController .left.> paymentPage
        payController ..> bill

        c -up- paymentPage


    }

    rectangle Help {
        boundary helpPage
        boundary helpSearchMask
        control helpController
        entity faqPDF

        helpController ..> helpPage
        helpController ..> faqPDF
        helpController ..> helpSearchMask

        c -up- helpPage
        c -up- helpSearchMask

    }

    rectangle Management {

        boundary managementOverview
        control revenueController
        entity revenueList

        m -down- managementOverview
        m - parkhausMainPage

        parkhausController ..> revenueController
        revenueController ..> managementOverview
        revenueController ..> revenueList
        revenueController ..> bill

    }

    rectangle ParkingSpace {
        boundary parkCarMask
        boundary parkCar
        control parkingSpaceController
        entity availableSpace


        parkingSpaceController .up.> parkCarMask
        parkingSpaceController .up.> parkCar
        parkingSpaceController .up.> availableSpace

        c - parkCarMask
        c - parkCar





    }

    parkhausController .up.> parkingSpaceController
    parkhausController .left.> payController
    parkhausController .down.> helpController
    parkhausController .down.> parkhausMainPage
    c - parkhausMainPage


}

@enduml