@startuml
'https://plantuml.com/sequence-diagram


actor customer
boundary helpPage
boundary helpSearchMask
control helpPageController
control faqDatabaseServletController
entity faqDatabaseServlet



entity searchResultList

autonumber

customer -> helpPage: start help page
helpPage -> helpPageController: start help mask
helpSearchMask <- helpPageController: show help mask
customer <-- helpSearchMask: help search mask
customer -> helpSearchMask: enter keyword/s (x)
customer -> helpSearchMask: start search for keyword/s (x)
helpSearchMask -> faqDatabaseServletController : start search for x
faqDatabaseServletController -> faqDatabaseServlet: SQL-Query
faqDatabaseServlet -> faqDatabaseServletController: sends results
faqDatabaseServletController --> searchResultList: new
searchResultList --> faqDatabaseServletController:
faqDatabaseServletController -> faqDatabaseServletController : asHTML()
faqDatabaseServletController --> helpSearchMask: list of results in HTML
helpSearchMask --> customer: filtered faqDatabase
@enduml
'created: 21.5.21: bella, lukas, rahgawi
'edited: 24.5.21: bella, lukas