
@startuml
'https://plantuml.com/class-diagram
'Erstellt von Rahgawi
actor Customer
boundary index
boundary CheckoutAuthenticationView
boundary CheckoutView
boundary Paymethod
control Level1Servlet
control CheckoutAuthenticationServlet
control CheckoutServlet
control PaymethodServlet
entity CheckoutModel
Customer -> index : press CHECKOUT-Button
index -> Level1Servlet : start CheckoutAuthentication-Mask
Level1Servlet -> CheckoutAuthenticationView : show CheckoutAuthentication-Mask
CheckoutAuthenticationView --> Customer : CheckoutAuthentication-Mask

@enduml