@startuml
'https://plantuml.com/sequence-diagram
actor Customer
boundary index
boundary ManagementAuthenticationView
boundary ManagementView
boundary AverageRevenueByCustomerTypeChart
boundary AverageRevenueByVehicleTypeChart
boundary IncomeChart
boundary KundenChart
control ManagementAuthenticationServlet
control ManagementServlet
entity ManagementModel
Customer -> index : press MANAGEMENT-Button
index -> Level1Servlet : start ManagementAuthenticationMask
Level1Servlet -> ManagementAuthenticationView : show ManagementAuthenticationMask
ManagementAuthenticationView --> Customer : ManagementAuthenticationMask


@enduml