@startuml
'https://plantuml.com/sequence-diagram
actor Customer
boundary Parkhaushomepage
boundary index
boundary CheckoutAuthenticationView
boundary ManagementAuthenticationView
control FirstpageServlet
control Level1Servlet
control CheckoutAuthenticationServlet
control ManagementAuthenticationServlet
entity ParkhausModel

@enduml